spring:
  application:
    name: activityservice
  data:
    mongodb:
      uri: mongodb://localhost/aiactivityservice
      database: aiactivityservice
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer:  org.springframework.kafka.support.serializer.JsonSerializer


kafka:
  topic:
    name : activity-events

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
server:
  port: 8082


logging:
  level:
    com.netflix.eureka: DEBUG
    org.springframework.kafka: INFO
    org.springframework.web.reactive: DEBUG